datawrapper/orm

models/Theme.js, package-lock.json, package.json, tests/theme/theme-1.test.js, tests/theme/theme-2.test.js, utils/theme.js
* added getter and setter methods for `theme.data` which is a JSON object stored in a TEXT column. the getter will automatically parse the JSON and the setter will stringify the value.
* likewise, I added getter and setter methods for `theme.assets`
* added `theme.getMergedData` for retrieving "flattened" theme data, which is the theme data with all data of "extended" themes merged into it
* added `theme.getMergedAssets` for retrieving all combined theme assets
* added new helper function `getAllMergedThemes()` to `@datawrapper/orm/utils/theme`. I thought it might be best to put utility functions that are exclusively for getting or setting data using the ORM into the `orm/utils` folder (instead of `@datawrapper/shared`). let me know if you have objections.
* added tests for the above
=> get "merged" theme data and assets

tests/action/action.test.js, utils/action.js
this PR adds a orm util function `logAction` for, well, logging user actions to our `actions` table. It's more or less a straight port of our old `Action::logAction()` function [in PHP](https://github.com/datawrapper/datawrapper/blob/master/lib/core/build/classes/datawrapper/Action.php#L18-L31).
=> add logAction util function

package-lock.json, package.json
this PR is an attempt to solve the Github security warning about `lodash.merge` < 4.6.2. The package was required by `concordance` which is required by `ava`. So I ran `npm install ava@latest` and `npm update` which seemed to have fixed it.
After updating `ava` the tests threw errors because ava is now trying to execute all `*.js` files in the `tests/` folder, which included our `config.tpl.js` etc. I fixed it by adding the `ava` config in package.json.
=> update ava and other dependencies to solve github security warning

README.md, index.js, package.json, plugins/orm-test/orm.js, tests/config.ci.js, tests/plugin-loader/plugin-loader.test.js, utils/plugins.js
Plugins are at the core of Datawrapper and following `datawrapper/api` and to some degree `datawrapper/frontend` the ORM gets them too.
The plugin API for the ORM closely follows what is done for `datawrapper/api`. 
* create a `orm.js` that exports a node module with a `register` method
* enable the plugin by adding it to `config.js`
* register plugin in your code.
This PR includes an example plugin, tests for the plugin loader and documentation.
After merging this PR we can build the basic River functionality for the new rendering pipeline.
=> feat: plugin functionality

index.js
When the database connection is created when initializing the ORM, it retries after a certain period if the db connect attempt was unsuccessful. Before the introduction of [orm plugins](https://github.com/datawrapper/orm/pull/9), this interval was **10 seconds**, and it retried **indefinitely**. Now, it's every **3 seconds**, and only up to **4 tries** before it throws an error. 
This gives the database 12 seconds to come up, which can be too short. I noticed this in the docker environment where all containers are started at the same time, and an initial start of a mySQL container can take a while for the database to initialize. This PR changes the behavior in the following ways:
- ORM retries to connect indefinitely, unless `config.orm.retryLimit` is set
- ORM retries every 3 seconds, …
=> Don't limit db connection retries unless configured

models/UserTeam.js
This PR fixes an error I caught a couple of times:
```
RangeError: Maximum call stack size exceeded
at Object.hasOwnProperty (<anonymous>)
at model.get (/app/node_modules/sequelize/lib/model.js:3363:35)
at model.get (/app/node_modules/@datawrapper/orm/models/UserTeam.js:13:44)
at model.get (/app/node_modules/sequelize/lib/model.js:3330:41)
at model.get (/app/node_modules/sequelize/lib/model.js:3364:33)
at model.get (/app/node_modules/@datawrapper/orm/models/UserTeam.js:13:44)
at model.get (/app/node_modules/sequelize/lib/model.js:3330:41)
at model.get (/app/node_modules/sequelize/lib/model.js:3364:33)
at model.get (/app/node_modules/@datawrapper/orm/models/UserTeam.js:13:44)
at model.get (/app/node_modules/sequelize/lib/model.js:3330:41)
at model.get …
```
=> fix infinite recursion bug when accessing userteam.team_role

models/Team.js
these attributes are no longer in use, the corresponding table columns will be removed soon
=> remove unused team attributed disabled and deleted

package-lock.json, package.json, tests/theme/theme-1.test.js
sequelize 6.0.0 has been published accidentally and is now no longer available via `npm`. 
see https://github.com/sequelize/sequelize/issues/11485 for more details
=> set sequelize dependency to 6.0.0-beta-4

models/ChartAccessToken.js
I tried running the render network locally and saw that rows in `chart_access_token` where written without `chart_id`. This caused the render-client to fail. With this little addition, it's fixed.
=> fix: add chart_id to model

models/AccessToken.js, models/AuthToken.js, models/ChartAccessToken.js, models/ExportJob.js, models/PluginData.js, models/UserData.js, tests/action.test.js, tests/authToken.test.js, tests/chartAccessToken.test.js, tests/export-job.test.js, tests/pluginData.test.js, tests/team.test.js, tests/userData.test.js
Some `sequelize` update has led to a change in behavior regarding to models that aren't completely defined. Fields that were missing in the model definition could still be set or updated in Sequelize queries. The current version of Sequelize requires defining all fields, either as model fields or as `foreignKeys` in a `belongsTo` relation.
This PR adds all the missing `foreignKey`s and some tests to confirm the values are actually set.
=> Add missing relation fields

models/Session.js
This PR fixes a bug that caused objects in the `session.data` column to not get serialized and instead being set to null, leading to various problem down the road regarding sessions with third-party sign-in providers.
I think this was simply an oversight when doing some refactoring to please eslint (https://github.com/datawrapper/orm/commit/135e8eac2ab79dba53ac6e98dc12ffa06057f49e#diff-c85e4fa0da25cc36124a84aa26ca5927R138)
=> Fix object serialization in Session.js

models/Session.js
This PR adds the fields `user_id` and `persistent` to the `Session` model. This will allow us to 
* delete all sessions related to a user
* delete all expired non-persistent sessions
I did omit the Sequelize model relation to `User` on purpose. For now I don't think we should add a foreign key constraint here, both because there are guest sessions without a user and I don't want to hazzle with conflict cases. For now this is just some extra information we're storing to make querying easier.
=> add optional user_id column to session table

.circleci/config.yml, index.js, models/Chart.js, package-lock.json, package.json, tests/chart/chart-1.test.js, tests/config._test.js, tests/config.ci.js, tests/index.js
Implements `publicId` functionality with Sequelize virtual fields.
> Virtual fields are fields that Sequelize populates under the hood, but in reality they don't even exist in the database.
> - https://sequelize.org/master/manual/getters-setters-virtuals.html#virtual-fields
This provides `chart.publicId` on any chart instance. If a `config.orm.chartIdSalt` is configured, the public ID is a MD5 hash based on chart ID, creation date and the salt.
Related schema PR: https://github.com/datawrapper/schemas/pull/11
=> feat: add chart.publicId virtual field

models/Chart.js
After using `chart.publicId` I encountered a weird crash of my code, with the following error: 
> `TypeError: Cannot read property 'toISOString' of undefined`
This  relates to the `this.createdAt.toISOString()` call in the getter of `publicId`. After some investigation it was caused by a `Chart.update` call. It looks like Sequelize tries to compute the public id when updating data and creates a `Chart` instance with `chart.id = null` and `chart.createdAt = undefined`. This caused the crash. By guarding against these missing properties, the problem is gone.
Again something learned from Sequelize.
=> fix: check for all values before computing public id hash

.github/CODEOWNERS, models/User.js, package-lock.json, package.json, tests/team.test.js, tests/user/user-3.test.js, tests/user/user-products.test.js
This PR adds the functionality to return the "active" product of a user. Like the [previous PHP implementation](https://github.com/datawrapper/datawrapper/blob/node-publishing/lib/core/build/classes/datawrapper/User.php#L324-L365] this checks both products through `UserProduct` and products through `TeamProduct`.
=> add user.getActiveProduct + tests

models/Chart.js
this PR adds a check for `chart.deleted` to `isEditableBy`. This will also affect `isPublishableBy`.
=> prevent edits of deleted charts

models/Chart.js
There were two errors in the `Chart.isEditableBy` check that currently result in it always being false for guests:
- guests have user objects, too, so we have to check `user.role === 'guest'`
- the sessionId is passed in directly, and not as an object that can be accessed like `session.id`
=> Check guest session correctly

models/User.js, tests/user/user-plugins.test.js
the idea is to replace [checks like these](https://github.com/datawrapper/api/blob/publish/src/routes/charts.js#L803-L817) in our API with a simple `await User.mayUsePlugin('export-pdf')`.
=> simplify user plugin check

models/User.js
This PR fixes a bug in `User.getActiveProduct`: Before, when a user had both a `userProduct` and `teamProduct` with the same priority, this method would return `null` as no product has a higher priority. This PR fixes it (by defaulting to the `userProduct`)
=> Fix product check for two products with equal priority

models/User.js
This PR adds `getActiveTeam` to the `User` model, which returns the currently selected team in Datawrapper. Implementation is 1:1 equivalent too the existing [PHP implementation](https://github.com/datawrapper/datawrapper/blob/master/lib/core/build/classes/datawrapper/User.php#L112-L126), just renamed from `getCurrentOrganization` to `getActiveTeam`. 
This is mostly used to determine where to place newly created charts.
=> Add User.getActiveTeam helper function

models/Chart.js, package-lock.json, package.json, tests/chart/chart-1.test.js
In order to support hash-publishing for teams, we need to determine whether to use the hash-based ID based on the team settings. To implement this, I replaced the 'virtual field' implementation with a model prototype method `getPublicId`. While it could have been implemented as a virtual field, the need for the team setting lookup caused too many needless database queries whenever a chart was loaded using the ORM, so I added the method so it's only loaded when needed.
The new team setting is part of the 'self-hosting' feature (though it could be enabled when using our CDN, too) and stored in `settings.publishTarget.hash_publishing`. The mixture of camel- and snake-case is annoying but consistent with the other options.
=> Move Chart.publicId to Chart.getPublicId method

models/Chart.js
API & frontend will both need to access this at times so it makes sense to move it to the ORM
=> Add Chart.getThumbnailHash

models/User.js
We shouldn't check `user.activate_token` for this, as it's deprecated but also currently (ab-)used for verification when a user changes their email
=> Check User.role for activation status

models/User.js
This PR fixes `User.mayUsePlugin`. Before, it only checked the `userPluginCache` to determine whether a plugin is usable. However, there are scenarios when that cache may be empty, in which we case we need to lookup the actual relation.
=> Fix user plugin check

models/User.js
`getUserData` expects parameter 1 [to be the user ID](https://github.com/datawrapper/orm/blob/master/utils/userData.js#L11), not a user object
=> Get correct active team

Makefile, models/Chart.js, models/ReadonlyChart.js, models/chartAttributes.js, models/index.js, tests/chartPublic.test.js
In many parts of the project, we want to use PublicChart as if it was Chart.
One solution to the problem would be to make Chart and PublicChart compatible (have them implement same methods). I believe this is (a) fragile and (b) can cause confusion by obscuring what model we're dealing with.
Therefore I propose a different solution: Copy the current state of PublicChart into a Chart and then work with the Chart only.
See https://github.com/datawrapper/api/pull/327 for usage.
=> Allow using PublicChart as Chart

models/Theme.js, tests/theme.test.js
It can happen on production that there is a theme with the `extend` property that points to a parent theme that doesn't exist. This makes `Theme.getMergedData()` crash.
Just stop walking up the theme tree when we encounter a theme that doesn't exist and return the data we've managed to gather sofar.
Also make sure we don't get stuck in an endless extend loop and add a unit test for that.
It's unfortunately impossible to add a unit test for the "missing extend theme" case, because the database schema of the testing database doesn't allow creating such a theme (foreign key must exist).
Related PR: https://github.com/datawrapper/plugin-admin-themes/pull/4
=> Theme.getMergedData: Don't crash on missing extend
